
// authReducer
export const UPDATE_AUTH_DATA = 'UPDATE_AUTH_DATA'
export const REMOVE_AUTH_DATA = 'REMOVE_AUTH_DATA'

// workspacesReducer
export const NEW_WORKSPACE_CREATED = 'NEW_WORKSPACE_CREATED'
export const UPDATE_ALL_WORKSPACES_DATA = 'UPDATE_ALL_WORKSPACES_DATA'
export const UPDATE_CURRENT_SELECTED_WORKSPACE = 'UPDATE_CURRENT_SELECTED_WORKSPACE'
export const RESET_CURRENT_SELECTED_WORKSPACES = 'RESET_CURRENT_SELECTED_WORKSPACES'
export const CHROME_APP_AUTHORIZE = 'CHROME_APP_AUTHORIZE'
export const CHROME_APP_UNAUTHORIZE = 'CHROME_APP_UNAUTHORIZE'

// channelsReducer
export const UPDATE_CURRENT_SELECTED_CHANNEL = 'UPDATE_CURRENT_SELECTED_CHANNEL'
export const GET_MESSAGES_FOR_CURRENT_CHANNEL = 'GET_MESSAGES_FOR_CHANNEL'
export const RESET_CURRENT_SELECTED_CHANNEL = 'RESET_CURRENT_SELECTED_CHANNEL'

// walkthroughActions
export const RUN_WALKTHROUGH = "RUN_WALKTHROUGH"
export const END_WALKTHROUGH = "END_WALKTHROUGH"
export const CHANGE_STEP = "CHANGE_STEP"
export const CHANGE_PROP_OBJECT = "CHANGE_PROP_OBJECT"

// secureStorageActions
export const ADD_PRIVATE_KEY = 'ADD_PRIVATE_KEY'
export const ADD_DECRYPTED_PRIVATE_KEY = 'ADD_DECRYPTED_PRIVATE_KEY'
export const REMOVE_PRIVATE_KEY = 'REMOVE_PRIVATE_KEY'
export const REMOVE_DECRYPTED_PRIVATE_KEY = 'REMOVE_DECRYPTED_PRIVATE_KEY'
export const CLEAR_SECURE_STORAGE = 'CLEAR_SECURE_STORAGE'

// storyDemoReducer
export const ADD_STEP = 'ADD_STEP'
export const UPDATE_STEP = 'UPDATE_STEP'
export const DELETE_STEP = 'DELETE_STEP'
export const ADD_TRANSITION = 'ADD_TRANSITION'
export const UPDATE_TRANSITION = 'UPDATE_TRANSITION'
export const DELETE_TRANSITION = 'DELETE_TRANSITION'
export const UPDATE_STORY_DEMO = 'UPDATE_STORY_DEMO'
export const UPDATE_RENDER_STEPS = 'UPDATE_RENDER_STEPS'

export const UPDATE_SCREEN = 'UPDATE_SCREEN'

export const ADD_STEP_ZOOM_SPAN = 'ADD_STEP_ZOOM_SPAN'
export const DELETE_STEP_ZOOM_SPAN = 'DELETE_STEP_ZOOM_SPAN'
export const UPDATE_STEP_ZOOM_SPAN = 'UPDATE_STEP_ZOOM_SPAN'


export const ADD_ZOOM_SPAN = 'ADD_ZOOM_SPAN'
export const DELETE_ZOOM_SPAN = 'DELETE_ZOOM_SPAN'
export const UPDATE_ZOOM_SPAN = 'UPDATE_ZOOM_SPAN'

export const DELETE_STEP_AUDIO = 'DELETE_STEP_AUDIO'

export const ADD_STEP_AUDIO = 'ADD_STEP_AUDIO'
