// Top 200 Google Fonts by popularity (from fonts.google.com/metadata/fonts).
export default [
  'Roboto',
  'Google Sans',
  'Open Sans',
  'Inter',
  'Montserrat',
  'Poppins',
  'Lato',
  'Noto Sans JP',
  'Arimo',
  'Roboto Condensed',
  'Oswald',
  'Roboto Mono',
  'Raleway',
  'Playfair Display',
  'Noto Sans',
  'Rubik',
  'DM Sans',
  'Outfit',
  'Manrope',
  'Kanit',
  'Nunito',
  'Merriweather',
  'Nunito Sans',
  'Work Sans',
  'Bebas Neue',
  'Archivo Black',
  'PT Sans',
  'Roboto Slab',
  'Figtree',
  'Plus Jakarta Sans',
  'Ubuntu',
  'Noto Sans KR',
  'Noto Sans TC',
  'Prompt',
  'Saira',
  'IBM Plex Sans',
  'Share Tech',
  'Karla',
  'Lora',
  'Black Ops One',
  'JetBrains Mono',
  'Bricolage Grotesque',
  'Source Code Pro',
  'Heebo',
  'Mulish',
  'Noto Serif',
  'Source Sans 3',
  'Titillium Web',
  'Cormorant Garamond',
  'Quicksand',
  'PT Serif',
  'Noto Color Emoji',
  'Archivo',
  'Barlow',
  'Libre Baskerville',
  'Lobster Two',
  'Google Sans Flex',
  'Jost',
  'Noto Sans SC',
  'Libre Franklin',
  'Barlow Condensed',
  'Smooch Sans',
  'Fjalla One',
  'Changa One',
  'Noto Serif JP',
  'Anton',
  'Cairo',
  'Fira Sans',
  'Inconsolata',
  'Mukta',
  'Sora',
  'Assistant',
  'Alfa Slab One',
  'Hind Siliguri',
  'Lexend',
  'Space Grotesk',
  'Instrument Serif',
  'Inter Tight',
  'EB Garamond',
  'Roboto Flex',
  'Fraunces',
  'Schibsted Grotesk',
  'IBM Plex Mono',
  'Nanum Gothic',
  'Orbitron',
  'Public Sans',
  'Rajdhani',
  'DM Serif Display',
  'M PLUS Rounded 1c',
  'Geist',
  'Red Hat Display',
  'Caveat',
  'Josefin Sans',
  'Fredoka',
  'Cabin',
  'Dancing Script',
  'Noto Sans Telugu',
  'Crimson Text',
  'Bitter',
  'Ramabhadra',
  'Bungee',
  'Dosis',
  'Anek Telugu',
  'Exo 2',
  'Pacifico',
  'Cinzel',
  'Lilita One',
  'PT Sans Narrow',
  'Gravitas One',
  'Overpass',
  'Tajawal',
  'Urbanist',
  'Noto Sans Arabic',
  'Teko',
  'Bodoni Moda',
  'Hind',
  'Comfortaa',
  'Noto Sans Khmer',
  'Oxygen',
  'Shadows Into Light',
  'Instrument Sans',
  'Maven Pro',
  'Hanken Grotesk',
  'Slabo 27px',
  'Lobster',
  'Space Mono',
  'Abril Fatface',
  'M PLUS 1p',
  'Onest',
  'Barlow Semi Condensed',
  'League Spartan',
  'DM Mono',
  'Arvo',
  'Questrial',
  'Abel',
  'Zen Kaku Gothic New',
  'Chakra Petch',
  'Geist Mono',
  'Newsreader',
  'IBM Plex Sans Arabic',
  'Sofia Sans',
  'Alumni Sans',
  'Syne',
  'Play',
  'Saira Condensed',
  'Cormorant',
  'Great Vibes',
  'Permanent Marker',
  'Satisfy',
  'Noto Serif TC',
  'Red Hat Text',
  'Albert Sans',
  'Vollkorn',
  'Archivo Narrow',
  'Noto Serif SC',
  'Zen Maru Gothic',
  'Courier Prime',
  'Merriweather Sans',
  'Roboto Serif',
  'Varela Round',
  'Baloo 2',
  'Asap',
  'Russo One',
  'Spectral',
  'Righteous',
  'Noto Kufi Arabic',
  'Unbounded',
  'Fira Sans Condensed',
  'Frank Ruhl Libre',
  'Asap Condensed',
  'Alegreya Sans',
  'Cardo',
  'Source Serif 4',
  'Domine',
  'Nanum Myeongjo',
  'Signika',
  'Yanone Kaffeesatz',
  'DM Serif Text',
  'Sarabun',
  'Crimson Pro',
  'IBM Plex Sans Condensed',
  'Rethink Sans',
  'LINE Seed JP',
  'Noto Serif KR',
  'News Cycle',
  'Viga',
  'Catamaran',
  'Amiri',
  'Atkinson Hyperlegible',
  'Hammersmith One',
  'Libre Caslon Text',
  'Montserrat Alternates',
  'Zilla Slab',
  'Special Elite',
  'Be Vietnam Pro',
  'Shippori Mincho',
  'Almarai',
  'Antic Slab',
  'Yellowtail',
  'Acme'
]
